name: Run tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test_on_linux:
    name: Test project on linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: npx hardhat test